config/routes.rb
Pakuhaji::Application.routes.draw do

  get "homes_profile" => "homes#profile", :as => "profile_home"
  get "homes_fasility" => "homes#fasility", :as => "fasility_home"
  get "homes_game" => "homes#game", :as => "game_home"
  get "homes_packet" => "homes#packet", :as => "packet_home"
  get "homes_gallery" => "homes#gallery", :as => "gallery_home"
  get "homes_gallery_show/:id" => "homes#gallery_show", :as => "gallery_show_home"
  
  
  get "sign_up" => "admins#new", :as => "sign_up"
  get "login" => "admins#new", :as => "login"
 resources :sessions
 resources :admins
 resources :articles
 resources :homes
 resources :profiles
 resources :fasilities
 resources :games
 resources :packets
 resources :galleries
 resources :sliders
 resources :vacation_packets
 resources :additional_packets
 resources :reservations do
   collection do 
     get ':id/update_status' => "reservations#update_status", :as => "update_status"
     get 'search' => "reservations#search", :as => "search"
   end
 end
 resources :customers
 resources :foods
 root :to => "homes#index"

end

app/models/vacation_packet.rb
class VacationPacket < ActiveRecord::Base
  #belongs_to :reservation,dependent: :delete
end

app/controllers/vacation_packets_controller.rb
class VacationPacketsController < ApplicationController
before_action :check_current_admin, only: [:new, :create, :edit, :update, :destroy, :index]
  layout "admin_application"
  def index
    @vacation_packet = VacationPacket.page(params[:page]) .per(5)
  end
  
  def new
    @vacation_packet = VacationPacket.new  
  end

   def create
    @vacation_packet = VacationPacket.new(vacation_packet_params)
    if @vacation_packet.save
      redirect_to action: 'index', notice: 'User was successfully created.'
    else
      render action: 'new', alert: 'User could not be created' 
    end
  end

   def update
     @vacation_packet = VacationPacket.find_by_id(params[:id])
      if @vacation_packet.update(vacation_packet_params)
      flash[:notice] = "Success Update Record"
      redirect_to action: 'index'
    else
      flash[:error] = "Data Not Valid"
      render 'edit'
    end
  end
  
  def edit
    @vacation_packet = VacationPacket.find_by_id(params[:id])
  end

  def show
      @vacation_packet = VacationPacket.find_by_id(params[:id])
  end
  
   def destroy
     @vacation_packet = VacationPacket.find_by_id(params[:id])
      if @vacation_packet.destroy
      flash[:notice] = "Success Delete a Record"
      redirect_to action: 'index'
    else
      flash[:error] = "Data Not Valid"
      render 'edit'
    end
    
  end

private
    # Never trust parameters from the scary internet, only allow the white list through.
    def vacation_packet_params
      params.require(:vacation_packet).permit(:title, :qty_game, :price_kid, :price_adult)
    end
end

app/views/vacation_packets/_list_vacation_packet.html.erb
<div class="col-sm-10 col-sm-offset-2 col-lg-10 col-lg-offset-2 main">			
	<br/><br/><br/>
	<div class="col-xs-12">               
<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">List Paket Wisata</div>
					<br/>
					<div class="container col-sm-2 side pull-right ">	
                <%= link_to 'Tambah Paket', new_vacation_packet_path,:class => 'btn btn-primary  fa fa-trash-o ' %>
                </div>
                <br/><br/>
                <div class="container col-sm-2 side pull-right ">
                <%= paginate @vacation_packet, :window => 5 %>
                </div>
                <br/><br/>
					<div class="panel-body">
						<table data-toggle="table" data-url="tables/data1.json"
						data-select-item-name="toolbar1"  data-sort-name="name" data-sort-order="desc">
                    
                    <thead>
                      <tr>
                        <th>Nama Paket</th>
                        <th>Jumlah Permainan</th>
                        <th>Harga Anak</th>
                        <th>Harga Dewasa</th>
                        <th>Operasi</th>

                      </tr>
                    </thead>
                    <tbody>
                    	<% @vacation_packet.each do |vacation_packet|%>
                              <tr>
                               	<td><%= vacation_packet.title.truncate(20) %></td>
        						<td><%= vacation_packet.qty_game.truncate(20) %></td>
        						<td><%= vacation_packet.price_kid %></td>
        						<td><%= vacation_packet.price_adult %></td>
        						
                   			 <td><div class="btn-group" role="group">
                                  		
                                  		<%= link_to 'EDIT', edit_vacation_packet_path(vacation_packet.id),:class => 'btn btn-primary  fa fa-trash-o ' %>
       									<%= link_to "Hapus", vacation_packet,:class => 'btn btn-danger  fa fa-trash-o ', :confirm => 'Are you sure?', :method => :delete%> </div>
                                  </td>
                   			 </tr>
                   			 
                    		<% end %>
                    	</tbody>
                    <tfoot>
                      
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->

            </div><!-- /.col -->
          </div><!-- /.row -->
   </div>
   </div>
   </div>
   </div>
   

app/views/vacation_packets/edit.html.erb
<%= render 'admins/navigation'%>
<%= render 'admins/sidebar'%>
<br/><br/><br/>
<%= form_for @vacation_packet do |f| %>
<div class="col-sm-2">
	</div>
<div class="col-sm-7">
		<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">Edit Paket Wisata</div>
					<br/>
	<form class="form-horizontal" role="form">
		<div class="form-group">
			<%= f.label :title, "Nama Paket:", :class => "control-label col-sm-4" %>
			<div class="col-sm-7">
				<%= f.text_field :title, :class => 'form-control', :placeholder=>'Masukan Nama Paket'%>
			</div>
			<br/><br/>
			<%= f.label :qty_game, "Jumlah Permainan:", :class => "control-label col-sm-4" %>
			<div class="col-sm-7">
				<%= f.text_field :qty_game, :class => 'form-control', :placeholder=>'Masukan Jumlah Permainan'%>				
			</div>
			<br/><br/>	
			<%= f.label :price_kid, "Harga Anak:", :class => "control-label col-sm-4" %>
			<div class="col-sm-7">
				<%= f.text_field :price_kid, :class => 'form-control', :placeholder=>'Masukan Harga Anak'%>
			</div>
			<br/><br/>	
			<%= f.label :price_adult, "Harga Dewasa:", :class => "control-label col-sm-4" %>
			<div class="col-sm-7">
				<%= f.text_field :price_adult, :class => 'form-control', :placeholder=>'Masukan Harga Dewasa'%>
			</div>
			<br/><br/><br/>
				<%= f.submit "Simpan", :class => 'btn btn-default'%>
	</div>
				</form>
			</div>
		</div>
	</div>
<% end %>

app/views/vacation_packets/index.html.erb
<%= render 'admins/navigation'%>
<%= render 'admins/sidebar'%>
<%= render 'list_vacation_packet'%>

 

app/views/vacation_packets/new.html.erb
<%= render 'admins/navigation'%>
<%= render 'admins/sidebar'%>
<br/><br/><br/>
<%= form_for @vacation_packet do |f| %>
<div class="col-sm-2">
	</div>
<div class="col-sm-7">
		<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">Tambah Paket Wisata</div>
					<br/>
	<form class="form-horizontal" role="form">
		<div class="form-group">
			<%= f.label :title, "Nama Paket:", :class => "control-label col-sm-4" %>
			<div class="col-sm-7">
				<%= f.text_field :title, :class => 'form-control', :placeholder=>'Masukan Nama Paket'%>
			</div>
			<br/><br/>
			<%= f.label :qty_game, "Jumlah Permainan:", :class => "control-label col-sm-4" %>
			<div class="col-sm-7">
				<%= f.text_field :qty_game, :class => 'form-control', :placeholder=>'Masukan Jumlah Permainan'%>				
			</div>
			<br/><br/>	
			<%= f.label :price_kid, "Harga Anak:", :class => "control-label col-sm-4" %>
			<div class="col-sm-7">
				<%= f.text_field :price_kid, :class => 'form-control', :placeholder=>'Masukan Harga Anak'%>
			</div>
			<br/><br/>	
			<%= f.label :price_adult, "Harga Dewasa:", :class => "control-label col-sm-4" %>
			<div class="col-sm-7">
				<%= f.text_field :price_adult, :class => 'form-control', :placeholder=>'Masukan Harga Dewasa'%>
			</div>
			<br/><br/><br/>
				<%= f.submit "Simpan", :class => 'btn btn-default'%>
	</div>
				</form>
			</div>
		</div>
	</div>
<% end %>