config/routes.rb
Pakuhaji::Application.routes.draw do

  get "homes_profile" => "homes#profile", :as => "profile_home"
  get "homes_fasility" => "homes#fasility", :as => "fasility_home"
  get "homes_game" => "homes#game", :as => "game_home"
  get "homes_packet" => "homes#packet", :as => "packet_home"
  get "homes_gallery" => "homes#gallery", :as => "gallery_home"
  get "homes_gallery_show/:id" => "homes#gallery_show", :as => "gallery_show_home"
  
  
  get "sign_up" => "admins#new", :as => "sign_up"
  get "login" => "admins#new", :as => "login"
 resources :sessions
 resources :admins
 resources :articles
 resources :homes
 resources :profiles
 resources :fasilities
 resources :games
 resources :packets
 resources :galleries
 resources :sliders
 resources :vacation_packets
 resources :additional_packets
 resources :reservations do
   collection do 
     get ':id/update_status' => "reservations#update_status", :as => "update_status"
     get 'search' => "reservations#search", :as => "search"
   end
 end
 resources :customers
 resources :foods
 root :to => "homes#index"

end

app/views/admins/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">								
				<%= image_tag("Logo Polos.png", :class => "img-square", :width => "100" , :height => "80" ) %>
				<div class="container col-sm-1 side pull-right ">
					<li> <%= link_to 'Log-Out', session_path(current_admin.id), method: "DELETE", :class => "glyphicon glyphicon-th" %> </li>
					</div>
					<div class="container col-sm-8 side pull-right ">
						<h2>WISATA KUDA DAN WARUNG LIWET PAKUHAJI</h2>													
						</div>	
				</ul>
			</div>
								
		</div><!-- /.container-fluid -->
</nav>

app/views/admins/_sidebar.html.erb
<div class="main-sidebar">
  <!-- Inner sidebar -->
  <div class="sidebar">
	
		<ul class="nav menu">
			<br/><br/>
			<center><h4>Menu Website</h4></center>
			<li><%= link_to "Berita", articles_path , :class => "glyphicon glyphicon-th" %> </li>
			<li><%= link_to "Profil", profiles_path , :class => "glyphicon glyphicon-th" %> </li>
			<li><%= link_to "Fasilitas", fasilities_path , :class => "glyphicon glyphicon-th" %> </li>
			<li><%= link_to "Permainan", games_path , :class => "glyphicon glyphicon-th" %> </li>
			<li><%= link_to "Galeri", galleries_path , :class => "glyphicon glyphicon-th" %> </li>
			<li><%= link_to "Paket", packets_path , :class => "glyphicon glyphicon-th" %> </li>
			<li><%= link_to "Slider", sliders_path , :class => "glyphicon glyphicon-th" %> </li>
						
		</ul>
		<ul class="nav menu">			
			<center><h4>Menu Paket Wisata</h4></center>			
			<li class="parent ">
				<a aria-expanded="true" data-toggle="collapse" href="#sub-item-1">
					<span class="glyphicon glyphicon-th"></span>Master Paket Wisata <span href="#" class="icon pull-right"><em class="glyphicon glyphicon-s glyphicon-plus"></em></span> 
				</a>
				<ul class="children collapse" id="sub-item-1">
					<li>
						<%= link_to "Paket Wisata", vacation_packets_path, :class => "glyphicon glyphicon-share-alt" %>									
					</li>
					<li>
						<%= link_to "Makan", foods_path, :class => "glyphicon glyphicon-share-alt" %>									
					</li>
					<li>
						<%= link_to "Paket Tambahan", additional_packets_path, :class => "glyphicon glyphicon-share-alt" %>
					</li>
				</ul>
			</li>
			<li><%= link_to "Data Paket Wisata", reservations_path , :class => "glyphicon glyphicon-th" %> </li>			
		</ul>
		</div>
	</div><!--/.sidebar-->

app/views/admins/edit.html.erb
<h1>Admins#edit</h1>
<p>Find me in app/views/admins/edit.html.erb</p>

app/views/admins/index.html.erb
<%= render 'sidebar'%>
<%= render 'navigation'%>
<br/><br/><br/><br/><br/><br/><br/>
<div id="main-content" class="col-xs-10 col-sm-6 col-md-8 main pull-right">
	<form class="form-horizontal" role="form">
		<div class="form-group">
			<h1>SELAMAT DATANG ADMIN</h1>
			</div>
		</div>
	</form>

app/views/admins/new.html.erb
<%= render 'navigation'%>
<%= form_for @admin do |f| %>
 <div id="main-content" class="col-xs-12 col-sm-100 main pull-right">
  <form class="form-horizontal" role="form">
   <div class="form-group">
      <label class="control-label col-sm-2" for="pwd">Username:</label>
      <div class="col-sm-3">          
        <%= f.text_field :username, :size => 20, :class => 'form-control', :placeholder=>'Masukan Username' %> 
      </div>
    </div>
    <br>
    <div class="form-group">
      <label class="control-label col-sm-2" for="pwd">Password:</label>
      <div class="col-sm-3">
      <%= f.password_field :password, :size => 20, :class => 'form-control', :placeholder=>'Masukan Password' %> 
    </div>
    </div>
<div class="form-group">        
      <div class="col-sm-offset-1 col-sm-10">
        <button type="submit" class="btn btn-default">Submit</button>
		      </div>
		    </div>
    </div>


<% end %>