config/routes.rb
Pakuhaji::Application.routes.draw do

  get "homes_profile" => "homes#profile", :as => "profile_home"
  get "homes_fasility" => "homes#fasility", :as => "fasility_home"
  get "homes_game" => "homes#game", :as => "game_home"
  get "homes_packet" => "homes#packet", :as => "packet_home"
  get "homes_gallery" => "homes#gallery", :as => "gallery_home"
  get "homes_gallery_show/:id" => "homes#gallery_show", :as => "gallery_show_home"
  
  
  get "sign_up" => "admins#new", :as => "sign_up"
  get "login" => "admins#new", :as => "login"
 resources :sessions
 resources :admins
 resources :articles
 resources :homes
 resources :profiles
 resources :fasilities
 resources :games
 resources :packets
 resources :galleries
 resources :sliders
 resources :vacation_packets
 resources :additional_packets
 resources :reservations do
   collection do 
     get ':id/update_status' => "reservations#update_status", :as => "update_status"
     get 'search' => "reservations#search", :as => "search"
   end
 end
 resources :customers
 resources :foods
 root :to => "homes#index"

end

app/models/additional_packet.rb
class AdditionalPacket < ActiveRecord::Base
  #belongs_to :reservation,dependent: :delete
end

app/controllers/additional_packets_controller.rb
class AdditionalPacketsController < ApplicationController
before_action :check_current_admin, only: [:new, :create, :edit, :update, :destroy, :index]
  layout "admin_application"
  def index
    @additional_packet = AdditionalPacket.page(params[:page]) .per(5)
  end
  
  def new
    @additional_packet = AdditionalPacket.new  
  end

   def create
    @additional_packet = AdditionalPacket.new(additional_packet_params)
    if @additional_packet.save
      redirect_to action: 'index', notice: 'User was successfully created.'
    else
      render action: 'new', alert: 'User could not be created' 
    end
  end

   def update
     @additional_packet = AdditionalPacket.find_by_id(params[:id])
      if @additional_packet.update(additional_packet_params)
      flash[:notice] = "Success Update Record"
      redirect_to action: 'index'
    else
      flash[:error] = "Data Not Valid"
      render 'edit'
    end
  end
  
  def edit
    @additional_packet = AdditionalPacket.find_by_id(params[:id])
  end

  def show
      @additional_packet = AdditionalPacket.find_by_id(params[:id])
  end
  
   def destroy
     @additional_packet = AdditionalPacket.find_by_id(params[:id])
      if @additional_packet.destroy
      flash[:notice] = "Success Delete a Record"
      redirect_to action: 'index'
    else
      flash[:error] = "Data Not Valid"
      render 'edit'
    end
    
  end

private
    # Never trust parameters from the scary internet, only allow the white list through.
    def additional_packet_params
      params.require(:additional_packet).permit(:content, :price)
    end
end

app/views/additional_packets/_list_additional_packet.html.erb
<div class="col-sm-10 col-sm-offset-2 col-lg-10 col-lg-offset-2 main">			
	<br/><br/><br/>
	<div class="col-xs-12">              
<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">List Paket Tambahan</div>
					<br/>
					<div class="container col-sm-3 side pull-right ">	
                <%= link_to 'Tambah Paket Tambahan', new_additional_packet_path,:class => 'btn btn-primary  fa fa-trash-o ' %>
                </div>
                 <br/><br/>
                <div class="container col-sm-2 side pull-right ">
                <%= paginate @additional_packet, :window => 5 %>
                </div>
                <br/><br/>
					<div class="panel-body">
						<table data-toggle="table" data-url="tables/data1.json"
						data-select-item-name="toolbar1"  data-sort-name="name" data-sort-order="desc">
                    
                    <thead>
                      <tr>
                        <th>Keterangan</th>
                        <th>Harga</th>
                        <th>Operasi</th>

                      </tr>
                    </thead>
                    <tbody>
                    	<% @additional_packet.each do |additional_packet|%>
                              <tr>
                               	<td><%= additional_packet.content %></td>
        						<td><%= additional_packet.price %></td>        						
                   			 <td><div class="btn-group" role="group">                                  		
                                  		<%= link_to 'EDIT', edit_additional_packet_path(additional_packet.id),:class => 'btn btn-primary  fa fa-trash-o ' %>
       									<%= link_to "Hapus", additional_packet,:class => 'btn btn-danger  fa fa-trash-o ', :confirm => 'Are you sure?', :method => :delete%> </div>
                                  </td>
                   			 </tr>
                   			 
                    		<% end %>
                    	</tbody>
                    <tfoot>
                      
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->

            </div><!-- /.col -->
          </div><!-- /.row -->
   </div>
   </div>
   </div>
   </div>
   

app/views/additional_packets/edit.html.erb
<%= render 'admins/navigation'%>
<%= render 'admins/sidebar'%>
<br/><br/><br/>
<%= form_for @additional_packet do |f| %>
<div class="col-sm-2">
	</div>
<div class="col-sm-7">
		<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">Edit Paket Tambahan</div>
					<br/>
	<form class="form-horizontal" role="form">
		<div class="form-group">
			<%= f.label :content, "Keterangan : ", :class => "control-label col-sm-3" %>
			<div class="col-sm-7">
				<%= f.text_field :content, :class => 'form-control', :placeholder=>'Masukan Deskripsi Makanan'%>				
			</div>
			<br/><br/>
			<%= f.label :price, "Harga : ", :class => "control-label col-sm-3" %>
			<div class="col-sm-7">
				<%= f.text_field :price, :class => 'form-control', :placeholder=>'Masukan Harga'%>				
			</div>			
			</div>
			<br/><br/><br/>
				<%= f.submit "Simpan", :class => 'btn btn-default'%>
	</div>
				</form>
			</div>
		</div>
	</div>
<% end %>

app/views/additional_packets/index.html.erb
<%= render 'admins/navigation'%>
<%= render 'admins/sidebar'%>
<%= render 'list_additional_packet'%>

 

app/views/additional_packets/new.html.erb
<%= render 'admins/navigation'%>
<%= render 'admins/sidebar'%>
<br/><br/><br/>
<%= form_for @additional_packet do |f| %>
<div class="col-sm-2">
	</div>
<div class="col-sm-7">
		<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">Tambah Paket Tambahan</div>
					<br/>
	<form class="form-horizontal" role="form">
		<div class="form-group">
			<%= f.label :content, "Keterangan : ", :class => "control-label col-sm-3" %>
			<div class="col-sm-7">
				<%= f.text_field :content, :class => 'form-control', :placeholder=>'Masukan Deskripsi Makanan'%>				
			</div>
			<br/><br/>
			<%= f.label :price, "Harga : ", :class => "control-label col-sm-3" %>
			<div class="col-sm-7">
				<%= f.text_field :price, :class => 'form-control', :placeholder=>'Masukan Harga'%>				
			</div>			
			</div>
			<br/><br/><br/>
				<%= f.submit "Simpan", :class => 'btn btn-default'%>
	</div>
				</form>
			</div>
		</div>
	</div>
<% end %>